version: "3"

services:
  mongodb:
    container_name: ytparty-mongodb
    image: mongo:bionic
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ytparty-mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=CHANGEME
    restart: unless-stopped

  redis:
    container_name: ytparty-redis
    image: redis:latest
    ports:
      - 127.0.0.1:6379:6379
    restart: unless-stopped

volumes:
  ytparty-mongodb-data:
