services:
  frontend:
    container_name: ytparty-frontend
    build: ./frontend
    ports:
      - 3000:3000
  backend:
    container_name: ytparty-backend
    build: ./backend
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env
